process.stderr.write('fail!')
process.exit(1)
